name: package

on:
  push:
  schedule:
    - cron: 0 6 * * * # Run at about 11:30 PM Indian Standard Time

env:
  PKGS_DIR: /tmp/__pkgs__
  CCACHE_DIR: /tmp/ccache
  GIT_REMOTE: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  GIT_BRANCH: gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        if: always()
        with:
          key: cache-cutefish
          path: ${{ env.CCACHE_DIR }}
      - run: pacman -Syu --noconfirm
      - run: ./action.sh initialize 
      - run: ./action.sh build
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_BRANCH }}
          path: ${{ env.GIT_BRANCH }}
          fetch-depth: 0
      - run: ./action.sh publish
        if: always()
